# Build the site
[build]
  command = "npm run generate"
  publish = "dist"

# Assign all the post-processing
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1"
    Content-Security-Policy = "default-src 'self' https://www.notsocial.app/ https://d33wubrfki0l68.cloudfront.net https://images.dog.ceo/ data: 'unsafe-inline'"

[[plugins]]
  package = "netlify-plugin-image-optim"
