# Build the site
[build]
command = "npm run generate"
publish = "dist"

[build.processing]
skip_processing = true

[[redirects]]
from = "https://pang.netlify.com/*"
to = "https://pang.troyv.dev/:splat"
status = 301
force = true

# Custom headers
[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1"
Content-Security-Policy = "default-src 'self' https://www.notsocial.app/ https://d33wubrfki0l68.cloudfront.net https://images.dog.ceo/ data: 'unsafe-inline'"

[[plugins]]
package = "netlify-plugin-image-optim"
